#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
# ClipFeed – interactive .env bootstrap script
# Generates cryptographic secrets and writes a ready-to-use
# .env file so you can `make up` immediately.
# ─────────────────────────────────────────────────────────
set -euo pipefail

ENV_FILE=".env"
EXAMPLE_FILE=".env.example"

# ── helpers ──────────────────────────────────────────────

rand_secret() { openssl rand -base64 32 | tr -d '\n'; }
rand_password() { openssl rand -base64 18 | tr -d '\n/+='; }

green()  { printf '\033[1;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[1;33m%s\033[0m\n' "$*"; }
cyan()   { printf '\033[1;36m%s\033[0m\n' "$*"; }
red()    { printf '\033[1;31m%s\033[0m\n' "$*"; }

ask() {
  # ask PROMPT DEFAULT  →  prints answer
  local prompt="$1" default="$2"
  local answer
  if [[ -n "$default" ]]; then
    read -rp "$(cyan "$prompt") [${default}]: " answer
    echo "${answer:-$default}"
  else
    read -rp "$(cyan "$prompt"): " answer
    echo "$answer"
  fi
}

# ── pre-flight ───────────────────────────────────────────

if ! command -v openssl &>/dev/null; then
  red "Error: openssl is required but not found. Install it and re-run."
  exit 1
fi

echo ""
green "╔══════════════════════════════════════════╗"
green "║       ClipFeed – Environment Setup       ║"
green "╚══════════════════════════════════════════╝"
echo ""

if [[ -f "$ENV_FILE" ]]; then
  yellow "An existing .env file was found."
  read -rp "$(yellow 'Overwrite it? (y/N): ')" overwrite
  if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
    echo "Aborted – existing .env left untouched."
    exit 0
  fi
  cp "$ENV_FILE" "${ENV_FILE}.bak"
  yellow "Backup saved to ${ENV_FILE}.bak"
  echo ""
fi

# ── auto-generate secrets ────────────────────────────────

JWT_SECRET="$(rand_secret)"
ADMIN_JWT_SECRET="$(rand_secret)"
COOKIE_SECRET="$(rand_secret)"
WORKER_SECRET="$(rand_secret)"
MINIO_PASSWORD="$(rand_password)"
ADMIN_PASSWORD="$(rand_password)"

# ── interactive prompts (all have sane defaults) ─────────

echo "Press Enter to accept the default shown in brackets."
echo ""

ADMIN_USERNAME="$(ask 'Admin username' 'admin')"

echo ""
yellow "── Compose Profiles ──"
echo "  (empty) = base stack, no AI"
echo "  ai      = + scout (cloud LLM)"
echo "  ai,ollama = + scout + local Ollama"
COMPOSE_PROFILES="$(ask 'Compose profiles' '')"

echo ""
yellow "── Processing ──"
PROCESSING_MODE="$(ask 'Processing mode (transcode / copy)' 'transcode')"
MAX_WORKERS="$(ask 'Max concurrent worker jobs' '4')"
WHISPER_MODEL="$(ask 'Whisper model (tiny/base/small/medium/large)' 'medium')"

echo ""
yellow "── Storage ──"
STORAGE_LIMIT_GB="$(ask 'Storage limit (GB)' '50')"
CLIP_TTL_DAYS="$(ask 'Clip TTL (days)' '30')"

echo ""
yellow "── LLM (only relevant if using AI profiles) ──"
LLM_PROVIDER="$(ask 'LLM provider (ollama/openai/anthropic)' 'ollama')"
LLM_API_KEY="$(ask 'LLM API key (leave empty for local Ollama)' '')"
LLM_MODEL="$(ask 'LLM model name (empty for default)' '')"
OLLAMA_MODEL="$(ask 'Ollama model (when using local Ollama)' 'llama3.2:3b')"

# ── write .env ───────────────────────────────────────────

cat > "$ENV_FILE" <<EOF
# ┌──────────────────────────────────────────────────────┐
# │  Generated by setup.sh on $(date -Iseconds)  │
# └──────────────────────────────────────────────────────┘

# --- Docker Compose profiles ---
COMPOSE_PROFILES=${COMPOSE_PROFILES}

# For GPU support, uncomment (requires NVIDIA Container Toolkit):
# COMPOSE_FILE=docker-compose.yml:docker-compose.gpu.yml

# --- Secrets (auto-generated) ---
JWT_SECRET=${JWT_SECRET}
ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
COOKIE_SECRET=${COOKIE_SECRET}
WORKER_SECRET=${WORKER_SECRET}

# --- MinIO ---
MINIO_USER=clipfeed
MINIO_PASSWORD=${MINIO_PASSWORD}

# --- Admin ---
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# --- Processing ---
PROCESSING_MODE=${PROCESSING_MODE}
MAX_WORKERS=${MAX_WORKERS}
WHISPER_MODEL=${WHISPER_MODEL}
MAX_VIDEO_DURATION=3600
MAX_DOWNLOAD_SIZE_MB=2048
MIN_CLIP_SECONDS=15
MAX_CLIP_SECONDS=90
TARGET_CLIP_SECONDS=45

# --- Storage ---
STORAGE_LIMIT_GB=${STORAGE_LIMIT_GB}
CLIP_TTL_DAYS=${CLIP_TTL_DAYS}

# --- Score Updater ---
SCORE_UPDATE_INTERVAL=900

# --- LLM ---
LLM_PROVIDER=${LLM_PROVIDER}
LLM_BASE_URL=
LLM_API_KEY=${LLM_API_KEY}
LLM_MODEL=${LLM_MODEL}
OLLAMA_MODEL=${OLLAMA_MODEL}
EOF

echo ""
green "✓ .env written successfully!"
echo ""

# ── summary ──────────────────────────────────────────────

echo "┌─────────────────────────────────────────────┐"
echo "│  Generated credentials (save these!)        │"
echo "├─────────────────────────────────────────────┤"
printf "│  Admin user:     %-26s│\n" "$ADMIN_USERNAME"
printf "│  Admin password: %-26s│\n" "$ADMIN_PASSWORD"
printf "│  MinIO password: %-26s│\n" "$MINIO_PASSWORD"
echo "├─────────────────────────────────────────────┤"
echo "│  JWT, cookie & worker secrets were generated │"
echo "│  automatically -- see .env for full values.   │"
echo "└─────────────────────────────────────────────┘"
echo ""
green "Next steps:"
echo "  1. Review .env and tweak if needed"
echo "  2. Run:  make up"
echo "  3. Open: http://localhost"
echo ""
