import React from 'react';
import { createRoot } from 'react-dom/client';
import './shared/tokens.css';
import './shared/base.css';
import './shared/empty-state.css';
import './shared/ui/tabs.css';
import './shared/ui/bottom-sheet.css';
import './shared/ui/confirm-dialog.css';
import './app/nav.css';
import './features/auth/auth.css';
import './features/feed/feed.css';
import './features/ingest/ingest.css';
import './features/jobs/jobs.css';
import './features/saved/saved.css';
import './features/settings/settings.css';
import './features/admin/admin.css';
import './shared/install-prompt.css';
import App from './app/App';

createRoot(document.getElementById('root')).render(<App />);
